services:
  - type: web
    name: ecommers-angular
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npx ng build
    startCommand: node dist/ecommersAngular/server/server.mjs
    envVars:
      - key: NODE_ENV
        value: production
