services:
  - type: web
    name: ecommers-angular
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/ecommersAngular/server/server.mjs
    envVars:
      - key: NODE_ENV
        value: production
